### ISSUE TITLE
Rubocop в Github actions использует неправильный конфиг при использовании блока Exclude

### ISSUE THREAD

**Issue by alexamy** [alexamy/thinknetica-qna#8]
При таком `.rubocop.yml` появляются ошибки (на шаге проверки рубокопом):
```yaml
AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
```

А если убрать хэш `Exclude`, то работает.

_Originally posted by @alexamy in https://github.com/alexamy/thinknetica-qna/issues/2#issuecomment-729298934_
